# Generated by Django 5.2.9 on 2026-01-01 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='owner',
        ),
    ]
