# Generated by Django 5.2.9 on 2026-01-30 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_remove_hotel_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingroom',
            old_name='room',
            new_name='Room',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hote/'),
        ),
        migrations.AlterField(
            model_name='roomimg',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
