# Generated by Django 5.2.9 on 2026-02-07 15:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_rename_room_bookingroom_room_alter_hotel_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart_bookingRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartRoom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_room', to='hotel.room')),
                ('cartbooking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CartBookingRoom', to='hotel.cart_booking')),
            ],
            options={
                'unique_together': {('cartbooking', 'cartRoom')},
            },
        ),
    ]
