# Generated by Django 5.2.9 on 2026-02-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_cart_booking_cart_bookingroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_num',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
